### ISSUE TITLE
Load More Button

### ISSUE THREAD

**Issue by ustincameron** [Duder-onomy/simple-instagram-photo-scrape#2]
Interesting work! Is it possible to trigger the load more button before retrieving the json?

**Comment by Duder-onomy** [comment]
Instagram has a very awesome and very complete API to access all kinds of data. I recommend starting there. 

I wrote this lib because I didn't want the overhead of authenticating and dealing with the API when I only needed a few of the recent photos for a feed. 

If instagram does not allow you access for some reason or you dont want to deal with the API and all that nonsense. Here is what I would do next:

If you look at the network panel when clicking 'load more' on instagram, it is making a request to `instagram.com/query` It would not be too difficult to duplicate this request and get more images. 

This endpoint can be 'POST'ed to without authenticating.

If I wanted to get more instagram photos for some reason that would be where I would start. Try and reverse engineer that `form body` of the post request and see if you can get what you need. 

Keep in mind, this is against the Instagram privacy policy.
